version: "3.8"

services:
  mongodb:
    image: mongo:6
    container_name: bls_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  loan-api:
    build: ./api
    container_name: bls_loan-api
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/bls

volumes:
  mongo-data:
